wrappid/wrappid-app

src/components/StaticWebPage.js

fixing it with the solution 2: The CoreStack needs to be changed to CoreBox until it's fixed.
Ref #15

fix: :bug: fixing StaticWebPage for mobile devices

---

.github/workflows/pr-guardrails.yml
src/components/StaticWebPage.js

Update wrappid-app template from development branch

feat: ✨ : update wrappid-app template

---

src/components/layouts/WrappidAppLayout.js

Added wrappid-app version details in the footer of the page.
#17

feat: :sparkles: Added wrappid-app version details

---

.github/pull_request_template.md
CONTRIBUTING.md

add contributing guide lines and pr templates
Ref: #11

docs: contributing rules

---

.husky/pre-commit
.vscode/settings.json
package-lock.json
package.json
src/components/StaticWebPage.js
src/index.js
src/registry/ResourcesRegistry.js
src/styles/AppClasses.js

This PR changes end of lines of all files to "LF".
#26 
NA
NA
NA
@techoneel 
---

refactor: lint code

---

LICENSE

docs: 🔒 license added 

---

package-lock.json
package.json

Added author and changed license and homepage
Ref: #35

docs: :memo: changes in package.json

---

src/styles/DefaultAppStyles.js
src/styles/LargeAppStyles.js
src/styles/MediumAppStyles.js
src/styles/SmallAppStyles.js
src/styles/XLargeAppStyles.js
src/styles/XXLargeAppStyles.js
src/styles/index.js
src/styles/modules/DefaultModulesStyles.js
src/styles/modules/LargeModulesStyles.js
src/styles/modules/MediumModulesStyles.js
src/styles/modules/SmallModulesStyles.js
src/styles/modules/XLargeModulesStyles.js
src/styles/modules/XXLargeModulesStyles.js

Merge development branch into main branch

Merge development into main

---

.eslintrc.js
src/components/About.js
src/components/layouts/WrappidAppLayout.js
src/registry/ComponentsRegistry.js
src/registry/RoutesRegistry.js

PackageList to About and other necessary changes
Ref #45
---

fix(core): :zap: update component name and other impact handles

---

.eslintrc.js
src/components/PackageList.js
src/components/layouts/WrappidAppLayout.js
src/registry/ComponentsRegistry.js
src/registry/RoutesRegistry.js

Reverts wrappid/wrappid-app#48

Revert "fix(core): :zap: update component name and other impact handles"

---

src/components/StaticWebPage.js

project title and description added in StaticWebPage
ref #47
---

feat(core): :sparkles: project title and description added

---

src/components/StaticWebPage.js

fix(core): ⚡ update component name and other impact handles

---

src/components/About.js
src/registry/ComponentsRegistry.js
src/registry/RoutesRegistry.js

merge: development to main

---

src/components/About.js

Wrpd enhancement 32

---

src/components/StaticWebPage.js
src/components/layouts/WrappidAppLayout.js

added styles component and other additional details
---

added styles, component and other additional details

---

src/components/StaticWebPage.js

styling and UI related changes
ref #47
styling and UI related changes 
---

feat(core): :sparkles: styling and UI related changes 

---

src/components/About.js

add some labels, fix undefined issue
ref: #32
---

fix: :bug: add some labels, fix undefined issue

---

src/components/About.js
src/components/StaticWebPage.js

merge: from Development

---

package.json

remove homepage key causing error
Ref: #60
---

fix(global): :bug: remove homepage key

---

src/components/StaticWebPageContent.js

changes made to ui in StaticWebPage
ref #47
---

style(core): :art: changes made to ui

---

.github/workflows/app-deploy.yml.NOT_IN_USE
.github/workflows/create-release.yml.NOT_IN_USE
.github/workflows/create-tag.yml..NOT_IN_USE
.github/workflows/create-tag.yml.NOT_IN_USE

Add sample worklows for CI/CD
Ref: #69
---

ci(config): :wrench: add sample worflows

---

.github/workflows/app-deploy.yml.NOT_IN_USE
.github/workflows/create-release.yml.NOT_IN_USE
.github/workflows/create-tag.yml.NOT_IN_USE

merge: development into main

---

.husky/pre-commit

restrict commiting into development
Ref: #73
---

enhancement: improve pre-commit condition

---

src/components/Layouts.js
src/components/layouts/AppDrawerLayout.js
src/registry/ComponentsRegistry.js
src/registry/RoutesRegistry.js

fixed WrappidAppLayout and added Layouts page
Ref #75
Layout pages added Resolves #75.
wrappid/core#130
Not yet done
---

feat(core): :art: basic layout related page added

---

package-lock.json
package.json

Update eslint-plugin-etc 2.0.2 to 2.0.3
#79
---

dependency: :arrow_up: update eslint-plugin-etc

---

wrappid.conf.json

removed default theme from wrappid.conf.json in wrappid-app
ref: #75
---

refactor(core): :zap: removed default theme from wrappid.conf.json

---

src/components/StaticWebPageContent.js

fullstop added to the project description in static web page
ref: #68
---

fix(core): :recycle: fullstop added to the project description

---

.github/workflows/pr-guardrails.yml
.gitignore
package-lock.json
package.json

Description
Resolves #84  and #85

enhancement: pr guardrails and package.json dependencies.

---

.github/workflows/app-deploy.yml.NOT_IN_USE
.gitignore

Add REMOTE_PATH_OF_PROJECT_DEPLOYMENT_PATH key
#88 
---

ci(config): 🔧 update ci config for deploy 

---

src/components/AppComponentContent.js
src/components/AppComponentSection.js
src/components/Section.js
src/registry/RoutesRegistry.js
src/registry/ThemesRegistry.js
src/themes/theme2.json
src/themes/theme3.json

themes & section related update
---

bugfix: themes & section related update

---

.wrappid/wrappid.meta.json
package-lock.json
package.json

Add missing wrappid packages key.
Fix wrong projectName in wrappid.meta.json
#94 
---

enhancement: add missing wrappid packages key

---

package-lock.json
src/components/AppComponentContent.js
src/components/layouts/ComplexLayout.js
src/components/layouts/ComplexLayoutPage.js
src/components/layouts/CoreLayoutItem.js
src/components/layouts/CoreLayoutPlaceholder.js
src/components/layouts/LayoutManager.js
src/components/layouts/LayoutManagerTest.js
src/registry/ComponentsRegistry.js
src/registry/RoutesRegistry.js

Development support added to wrappid app for handing layout manager.
Reference issue #76
#76 
N/A
N/A
N/A
N/A
Thank you for your contribution!-->
---

chore: development support added to wrappid app for handing layout manager

---

.github/workflows/create-tag.yml
.wrappid/wrappid.meta.json

Add wrTemplateVersion key for maintaining wrappid template boilerplates, enable create-tag.yml for tag creation on Pull Requests.
#23
---

ci: wrappid-app template versioning

---

src/components/AppComponentContent.js
src/components/AppComponentSection.js

wrapped the texts in coretypographybody1
Ref: #99

fix: :bug: fix the texts

---

src/components/AppComponentContent.js
src/components/AppComponentSection.js
src/components/layouts/WrappidAppLayout.js

Fixes the error with text not showing.

bug: boilerplate page ui

---

package-lock.json

Fix runtime security issues, update package-lock.json to patched packages
#107

chore(config): :lock:  fix runtime security issues

---

src/components/AppComponentContent.js
src/components/AppComponentSection.js

links added and buttons removed from static page
ref: #113
---

refactor(core): :ambulance: links added and buttons removed

---

src/components/AppComponentContent.js
src/components/AppComponentSection.js

release notes and other links added in staticPage
ref: #113
---

refactor(core): :ambulance: release notes and other links added

---

.github/workflows/pr-guardrails.yml
.versionrc.json
package-lock.json
package.json

1. This pull request adds `.versonrc.json` file to configure commit message by workflows for tag creation of wrappid-app type projects.
2. This pull request also modifies package-lock.json where @wrappid/native-mobile is installed via `npm ci --force` as this package is causing dependencies conflicts during installation.
Ref: #117 
---

bugfix: fixes commit message during tag creation by workflows.

---

package-lock.json
package.json

set wrappid packages version to latest
#122 
---

fix(config): :pushpin: pin wrappid packages to latest

---

src/components/AppComponentContent.js

static page design related change
Ref #113
---

fix(core): :bug: static page design related change

---

res/android/app/build.gradle

add sample build.gradle file for android.
#135
---

feat(core): :sparkles: add sample build.gradle file for android
